### ISSUE TITLE
  vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:158 - Throws ssl issue.

### ISSUE THREAD

**Issue by DementedWeasel1971** [adrenallen/ai-agents-laravel#17]
![image](https://github.com/adrenallen/ai-agents-laravel/assets/11000777/cccced9f-2626-4c20-b1c7-ade055826a2b)

Throw error when running cli.

Seems as though error with certificates on client side:
"
  cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.openai.com/v1/chat/completions

  at vendor\openai-php\client\src\Transporters\HttpTransporter.php:107
    103▕             if ($clientException instanceof ClientException) {
    104▕                 $this->throwIfJsonError($clientException->getResponse(), $clientException->getResponse()->getBody()->getContents());
    105▕             }
    106▕
  ➜ 107▕             throw new TransporterException($clientException);
    108▕         }
    109▕     }
    110▕
    111▕     private function throwIfJsonError(ResponseInterface $response, string|ResponseInterface $contents): void

  1   vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:211
      GuzzleHttp\Exception\RequestException::("cURL error 60: SSL certificate problem: unable to get local issuer certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://api.openai.com/v1/chat/completions")

  2   vendor\guzzlehttp\guzzle\src\Handler\CurlFactory.php:158
      GuzzleHttp\Handler\CurlFactory::createRejection()

"

I have xamp installed, running on localhost
PHP 8.1

**Comment by adrenallen** [comment]
Hey @DementedWeasel1971 thanks for providing all this detail!

I just setup xampp on my local, on php 8.1 and a default `example-app` Laravel 10 setup, and I wasn't able to replicate this issue. 😓

Are you able to curl the endpoint from your cli? I see in your screenshot it looks like you had it working above, was that not an Open AI bot?

**Comment by DementedWeasel1971** [comment]
I "corrected" this in my dev environment:
![image](https://github.com/adrenallen/ai-agents-laravel/assets/11000777/cdf8ad98-63d0-4f65-b361-e36f4608b891)

But I will have to find a safe way for prod.  This is what I did:
In guzzle client.php I set the verify flag to false

![image](https://github.com/adrenallen/ai-agents-laravel/assets/11000777/6ae46518-6d70-46de-a8b0-89fdbd4cc12c)


Not a safe play for prod, but made it work in dev.

 /**
     * Configures the default options for a client.
     */
    private function configureDefaults(array $config): void
    {
        $defaults = [
            'allow_redirects' => RedirectMiddleware::$defaultSettings,
            'http_errors' => true,
            'decode_content' => true,
            'verify' => false,
            'cookies' => false,
            'idn_conversion' => false,
        ];

**Comment by DementedWeasel1971** [comment]
You are welcome to close the item from a dev perspective.  I suspect it would assist future adventurers to have this solve in some Q&A, but with a cavate that this is cool for dev but not cool for prod.

**Comment by adrenallen** [comment]
> I "corrected" this in my dev environment: ![image](https://private-user-images.githubusercontent.com/11000777/313459520-cdf8ad98-63d0-4f65-b361-e36f4608b891.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDg2MDIsIm5iZiI6MTcxMDcwODMwMiwicGF0aCI6Ii8xMTAwMDc3Ny8zMTM0NTk1MjAtY2RmOGFkOTgtNjNkMC00ZjY1LWIzNjEtZTM2ZjQ2MDhiODkxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDIwNDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTU0YjgzMWYyMDA1OTc5YzExZTNiYWU4MGU2NGNkMjIzZTIyM2JmNTc3YzgwNDMyMTMyMWVmYjdmYmQ4YWZlOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.dHlSoUNbzYPoZAFZRKi4Ua1O9DSfuraBKszN8fOFsRw)
> 
> But I will have to find a safe way for prod. This is what I did: In guzzle client.php I set the verify flag to false
> 
> ![image](https://private-user-images.githubusercontent.com/11000777/313459648-6ae46518-6d70-46de-a8b0-89fdbd4cc12c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MDg2MDIsIm5iZiI6MTcxMDcwODMwMiwicGF0aCI6Ii8xMTAwMDc3Ny8zMTM0NTk2NDgtNmFlNDY1MTgtNmQ3MC00NmRlLWE4YjAtODlmZGJkNGNjMTJjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE3VDIwNDUwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU3YTdhY2U3Y2Q4ZDQ5ZTU2ZTQwZmYxNjRhYTExMTI4YWNhNThiOGQ1NjNjY2VlY2E3YTkyYmM5ZWEyZDcwODQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Gw0wCoNj6GmjGrtbkZqy1lMZ_Fmg1HeeIhVGZQwrnok)
> 
> Not a safe play for prod, but made it work in dev.
> 
> /** * Configures the default options for a client. */ private function configureDefaults(array $config): void { $defaults = [ 'allow_redirects' => RedirectMiddleware::$defaultSettings, 'http_errors' => true, 'decode_content' => true, 'verify' => false, 'cookies' => false, 'idn_conversion' => false, ];

Hmmm, you really shouldn't have to do this. But I will add a link here in the readme. If anyone else comes across this issue, please feel free to re-open and we can investigate further!
